#!/bin/bash

# colors
WHITE="\e[97m"
RED="\e[31m"
YELLOW="\e[33m"
GREEN="\e[32m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
BLACK="\e[30m"
ENDCOLOR="\e[0m"

# uptime
puptime="$(uptime -p)"
puptime=${puptime:3}

# memory
totalmem=$(free -m | grep -oP '\d+' | head -n 1)
currmem=$(free -m | grep -oP '\d+' | head -n 2 | tail -1)


# This function is from 
# TrinityCoder/center_text_in_bash.md on Github
function print_centered {

     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}

figlet -w $(tput cols) -c "fetch-ke"
print_centered "user: $(whoami)"
print_centered "hname: $(hostname)"
print_centered "distro: $(hostnamectl | sed -n -e 's/^.*Operating System: //p')"
print_centered "kernel: $(uname -r)"

print_centered "uptime: $puptime"
print_centered "shell: $(echo $SHELL)"
print_centered "processes: $(ps -e | wc -l)"
print_centered "memory: $currmem | $totalmem"


COLORS=$(echo -e "${WHITE}white${ENDCOLOR} ${RED}red${ENDCOLOR}  ${YELLOW}yellow${ENDCOLOR} ${GREEN}green${ENDCOLOR} ${BLUE}blue${ENDCOLOR} ${MAGENTA}magenta${ENDCOLOR} ${CYAN}cyan${ENDCOLOR}")
print_centered "                                                 colors: $COLORS"
